/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiExplainMatchRouteImport } from './routes/api/explain-match'
import { Route as ApiParseCustomMatchRouteImport } from './routes/api/parse-custom-match'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExplainMatchRoute = ApiExplainMatchRouteImport.update({
  id: '/api/explain-match',
  path: '/api/explain-match',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParseCustomMatchRoute = ApiParseCustomMatchRouteImport.update({
  id: '/api/parse-custom-match',
  path: '/api/parse-custom-match',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/explain-match': typeof ApiExplainMatchRoute
  '/api/parse-custom-match': typeof ApiParseCustomMatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/explain-match': typeof ApiExplainMatchRoute
  '/api/parse-custom-match': typeof ApiParseCustomMatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/explain-match': typeof ApiExplainMatchRoute
  '/api/parse-custom-match': typeof ApiParseCustomMatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/explain-match' | '/api/parse-custom-match'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/explain-match' | '/api/parse-custom-match'
  id: '__root__' | '/' | '/api/explain-match' | '/api/parse-custom-match'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiExplainMatchRoute: typeof ApiExplainMatchRoute
  ApiParseCustomMatchRoute: typeof ApiParseCustomMatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/explain-match': {
      id: '/api/explain-match'
      path: '/api/explain-match'
      fullPath: '/api/explain-match'
      preLoaderRoute: typeof ApiExplainMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parse-custom-match': {
      id: '/api/parse-custom-match'
      path: '/api/parse-custom-match'
      fullPath: '/api/parse-custom-match'
      preLoaderRoute: typeof ApiParseCustomMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiExplainMatchRoute: ApiExplainMatchRoute,
  ApiParseCustomMatchRoute: ApiParseCustomMatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
